services:
  postgres:
    image: postgres:17.4-alpine
    container_name: nepal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: nepal_user
      POSTGRES_PASSWORD: nepal_password
      POSTGRES_DB: nepal_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nepal_user -d nepal_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
